### ISSUE TITLE
Why attestations are manually crafted?

### ISSUE THREAD

**Issue by notastudio** [AppliedCryptoGroup/PoseCode#1]
Hello, I have read your paper and found it intriguing and inspiring. Since I am not familiar with ARM TrustZone used in the paper, I would like to ask how attestations work in the POSE system.
As far as I know, to ensure the integrity of attestations, the private key to sign them is controlled by the TEE vendors secretly. And the attestations are generated by APIs provided by TEE, rather than being generated manually by the developers. However, the private key and scripts to generate attestation signatures are provided in `PoseCode/SmartContract/attestations/`. In `POSEHostTests.c`, it looks like the attestation quote is manually crafted. That confuses me. Are attestations and corresponding signatures generated by developers manually in POSE? This may be dangerous as attestations can be forged in this way.
And an `ATTESTATION_AUTHORITY` is hard coded in the contract code. Who is he? Does it correspond to some TEE vendor?
```
address public constant ATTESTATION_AUTHORITY = 0x1dF62f291b2E969fB0849d99D9Ce41e2F137006e;
```

**Comment by MitjaSchlindwein** [comment]
You are correct that the TEE private keys never leave the TEEs. However, the test class / keys you referenced is for testing the component in isolation. Further, as the attestation authority is vendor-specific, we extracted the public key from one concrete instance. Note that this implementation is a research prototype and not ready for production.
